#!/bin/bash

if [ $SPIN ]; then
  # Link dotfiles
  ln -sf ~/dotfiles/.gitconfig ~/.gitconfig

  # Install packages
  sudo apt-get install -y ripgrep
else
  # Link dotfiles
  ln -sf $PWD/.gitconfig ~/.gitconfig
fi
